In [1]:
from deepface import DeepFace
#liveness
import tensorflow as tf

In [2]:
import cv2, numpy, datetime, keyboard

In [3]:
model = 'liveness.model'
model = tf.keras.models.load_model(model)

In [4]:
cap = cv2.VideoCapture(0)
font = cv2.FONT_HERSHEY_SIMPLEX

running = True

while running:
    state, frame = cap.read()
    if state!=True:
        break
    res  = DeepFace.find(frame, db_path="KnownFaces", enforce_detection=False, model_name='VGG-Face')
    
    
    
    # res
    if len(res[0]['identity'])>0:
        res[0]['identity']
        name = res[0]['identity'][0].split('/')[0].split('\\')[1]
        xmin = int(res[0]['source_x'][0])
        ymin = int(res[0]['source_y'][0])
        
        w = res[0]['source_w'][0]
        h = res[0]['source_h'][0]
        
        xmax = int(xmin + w)
        ymax = int(ymin + h)
        
        #liveness
        
        img = frame[ymin:ymax, xmin:xmax]
        img = cv2.resize(img, (32,32))
        img = img.astype('float')/255.0
        img = tf.keras.preprocessing.image.img_to_array(img)
        img = numpy.expand_dims(img, axis=0)

        liveness = model.predict(img)
        
        liveness = liveness[0].argmax()

        if liveness==1:
            cv2.rectangle(frame, (xmin,ymin),(xmax,ymax), (0,255,0),1)
            cv2.rectangle(frame, (xmin, ymin-25),(xmax, ymin),(255,255,255),-1)
            cv2.putText(frame, name, (xmin,ymin), cv2.FONT_HERSHEY_SIMPLEX, 1, (255,0,0),2,cv2.LINE_AA)
        else:
            cv2.rectangle(frame, (xmin,ymin),(xmax,ymax), (0,255,0),1)
            cv2.rectangle(frame, (xmin, ymin-25),(xmax, ymin),(255,255,255),-1)
            cv2.putText(frame, "FAKEEE", (xmin,ymin), cv2.FONT_HERSHEY_SIMPLEX, 1, (255,0,0),2,cv2.LINE_AA)
        
    cv2.imshow('attendance', frame)
    c = cv2.waitKey(1)

    if c == ord('q'):
        break

cap.release()
cv2.destroyAllWindows()

24-06-01 20:14:30 - Searching [[[ 38  34  33]
  [ 41  37  36]
  [ 33  31  29]
  ...
  [167 222 196]
  [166 222 197]
  [165 221 196]]

 [[ 37  34  32]
  [ 41  38  36]
  [ 36  34  33]
  ...
  [166 223 198]
  [165 223 198]
  [164 222 197]]

 [[ 35  34  31]
  [ 39  38  35]
  [ 37  35  34]
  ...
  [165 225 201]
  [165 226 200]
  [164 225 198]]

 ...

 [[133 139 156]
  [134 140 157]
  [138 142 160]
  ...
  [177 188 186]
  [182 194 192]
  [187 200 198]]

 [[134 138 156]
  [135 139 157]
  [136 140 158]
  ...
  [177 188 186]
  [182 194 192]
  [187 200 198]]

 [[134 138 156]
  [134 138 156]
  [134 138 156]
  ...
  [177 188 186]
  [182 194 192]
  [187 200 198]]] in 16 length datastore
24-06-01 20:14:34 - find function duration 4.404512882232666 seconds
1/1 [==============================] - 14s 14s/step
24-06-01 20:14:48 - Searching [[[ 34  34  28]
  [ 36  36  30]
  [ 38  39  34]
  ...
  [166 214 188]
  [165 213 187]
  [163 211 185]]

 [[ 36  36  30]
  [ 36  36  30]
  [ 36  36  32]
  ...
  [166 2